backend:
  name: github
  branch: new
  repo: opencollective/foundation-website
  base_url: https://foundation-website-git-new-opencollective.vercel.app
  auth_endpoint: api/begin

# publish_mode: editorial_workflow
media_folder: src/assets/uploads
public_folder: /assets/uploads
show_preview_links: true
local_backend: true

collections:
  - name: home
    label: 'Home sections'
    label_singular: 'section'
    folder: src/home
    extension: md
    format: yaml-frontmatter
    sortable_fields:
      - position
    create: false
    delete: false
    editor:
      preview: false
    fields:
      - name: title
        label: Title
        widget: string
      - name: hideInNavigation
        label: Hide in navigation
        widget: boolean
        required: false
        default: false
      - name: position
        label: Display position
        widget: number
        min: 0
        step: 1
      - name: body
        label: body
        widget: markdown
  - name: configurableContent
    label: Configurable content
    description: |
      Configurable structured content
    editor:
      preview: false
    files:
      - name: featuredCollectives
        label: Featured collectives
        label_singular: Featured collective
        file: src/_data/featuredCollectives.json
        fields:
          - name: featuredCollectives
            label: featured collectives
            label_singular: featured collective
            widget: list
            allow_add: true
            summary: '{{name}}'
            fields:
              - name: name
                label: Name
                widget: string
                required: true
              - name: heroImage
                label: Hero image
                widget: image
                allow_multiple: false
                required: true
              - name: heroImageAlt
                label: Alt text for hero image
                description: Alternative text description of image
                widget: string
                required: false
      - name: people
        label: People
        label_singular: person
        file: src/_data/people.json
        fields:
          - name: people
            label: people
            label_singular: person
            widget: list
            allow_add: true
            summary: '{{name}}'
            fields:
              - name: name
                label: Name
                widget: string
                required: true
              - name: profileImage
                label: Profile image
                widget: image
                allow_multiple: false
                required: true
              - name: department
                label: Department
                widget: relation
                collection: configurableContent
                file: people
                value_field: departments.*
                search_fields: ['name']
              - name: title
                label: Title
                widget: string
                required: true
              - name: administrativeArea
                label: State, Province, etc.
                widget: string
                required: false
              - name: country
                widget: relation
                collection: configurableContent
                file: geography
                value_field: 'countries.*.code'
                display_fields: ['countries.*.label']
                search_fields: ['countries.*.label', ' countries.*.code']
                required: true
              - name: linkedInUrl
                label: LinkedIn URL
                widget: string
                required: false
              - name: twitterUrl
                label: Twitter URL
                widget: string
                required: false
              - name: instagramUrl
                label: Instagram URL
                widget: string
                required: false
              - name: websiteUrl
                label: Website URL
                widget: string
                required: false
          - name: departments
            label: Departments
            label_singular: Department
            widget: list
            summary: '{{name}}'
            minimize_collapsed: true
            field:
              name: name
              label: Department name
              widget: string
      - name: geography
        label: Geography
        file: src/_data/geography.json
        fields:
          - name: countries
            widget: list
            minimize_collapsed: true
            fields:
              - name: label
                label: Label
                widget: string
              - name: code
                label: ISO country code
                widget: string
                pattern: ['[A-Z]{2}', 'Must be a two-character ISO code']
