backend:
  name: github
  branch: master
  repo: jboolean/art-coop

publish_mode: editorial_workflow
media_folder: src/assets/uploads
public_folder: /assets/uploads
show_preview_links: true
local_backend: true

collections:
  - name: sections
    label: "Home sections"
    label_singular: 'section'
    folder: src/sections
    extension: md
    format: yaml-frontmatter
    sortable_fields: 
      - position
    create: false
    delete: false
    editor:
      preview: false
    fields:
      - name: title
        label: Title
        widget: string
      - name: hideInNavigation
        label: Hide in navigation
        widget: boolean
        required: false
        default: false
      - name: position
        label: Display position
        widget: number
        min: 0
        step: 1
      - name: body
        label: body
        widget: markdown
