backend:
  name: github
  branch: master
  repo: jboolean/art-coop

publish_mode: editorial_workflow
media_folder: src/assets/uploads
public_folder: /assets/uploads
show_preview_links: true
local_backend: true

collections:
  - name: sections
    label: "Home sections"
    label_singular: 'section'
    folder: src/sections
    extension: md
    format: yaml-frontmatter
    sortable_fields: 
      - position
    create: false
    delete: false
    editor:
      preview: false
    fields:
      - name: title
        label: Title
        widget: string
      - name: hideInNavigation
        label: Hide in navigation
        widget: boolean
        required: false
        default: false
      - name: position
        label: Display position
        widget: number
        min: 0
        step: 1
      - name: body
        label: body
        widget: markdown
  - name: carousels
    label: Carousel data
    label_singular: carousel
    description: |
      Collections of data displayed in carousels
    files:
      - name: people
        label: People
        label_singular: person
        file: src/_data/people.json
        fields:
          - name: people
            label_singular: person
            widget: list
            allow_add: true
            summary: "{{name}} ({{personTitle}})"
            fields:
              - name: category
                widget: select
                options: 
                  - "Artists / Field Partners"
                  - "Grantmakers"
              - name: name
                label: Name
                widget: string
              - name: personTitle
                label: Title
                widget: string
              - name: url
                widget: string
                pattern: 
                  - https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)
                  - Must be a URL


