backend:
  name: github
  branch: new
  repo: opencollective/foundation-website
  base_url: https://foundation-website-git-new-opencollective.vercel.app
  auth_endpoint: api/begin

# publish_mode: editorial_workflow
media_folder: src/assets/uploads
public_folder: /assets/uploads
show_preview_links: true
local_backend: true

collections:
  - name: home
    label: 'Home sections'
    label_singular: 'section'
    folder: src/home
    extension: md
    format: yaml-frontmatter
    sortable_fields:
      - position
    create: false
    delete: false
    editor:
      preview: false
    fields:
      - name: title
        label: Title
        widget: string
      - name: hideInNavigation
        label: Hide in navigation
        widget: boolean
        required: false
        default: false
      - name: position
        label: Display position
        widget: number
        min: 0
        step: 1
      - name: body
        label: body
        widget: markdown
